# OS Catalog
Catalogue of novel operating systems

Somewhere after the fall in popularity of note-taking apps, perhaps recognizing that just note-taking is not enough and the deafening hype of LLMs, there was a sweet period of lull when a lot of people started boldly building new operating systems. This is a catalogue of such operating systems that I have come across. In the past, before the commercialization of computers, we had a plethora of operating systems with unique languages to interact with computers, like Symbolics, MULTICS, Burroughs, PARC, Star, Oberon, PLAN9, PL/8 etc. This spirit can only be glimpsed in pockets, and kudos to all those who keep the fire alive!

* UXN

Perhaps the best one to start off this catalog is the UXN/Varvara personal computing stack of [[https://100r.co][100 Rabbits]]. Such a great couple with such a radical vision!

[[UXN logo][./img/uxn-logo.jpg]]

[[UXN screenshot][./img/uxn-screenshot.jpg]]

They have documented their rationale in these two documents:
[[https://100r.co/site/tools_ecosystem.html][Tools Ecosystem]]
[[https://100r.co/site/weathering_software_winter.html][Weathering Software Winter]]

# Playbit

Daring effort from Rasmus Anderson and team to rebuild computer from scratch.

# Folk.computer

Omar Rizwan and Andreas Cuérvo

# Nette.io

# Interim

Something about Lisp draws people into construct OSes from ground up. Perhaps it is the simplicity of the language that acts as the foundation.

# RayvnOS

# MercuryOS

# Status Unknown

## [[https://bedrock.computer][Bedrock.computer]]
## [[https://new.computer][New.computer]]

# Other lists

[[https://github.com/jubalh/awesome-os][AwesomeOS by @jubalh]]
[[https://1.anagora.org/node/os][Anagora List]]

